import Header from "@/components/header";
import SubHeader from "@/components/subheader";

export const metadata = {
  title: "Single Advert",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <Header />
      <SubHeader title="Property Page" />
      {children}
    </>
  );
}
